app = "edu-echo"
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = "tcp"
  internal_port = 9000
  ports = [{ port = 9000 }]

[[services]]
  protocol = "udp"
  internal_port = 9001
  ports = [{ port = 9001 }]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024